"""add interpretation timestamp

Revision ID: 72a92f8f71a8
Revises: 
Create Date: 2026-04-12 16:24:04.735576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '72a92f8f71a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_records', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('learning_records', sa.Column('last_watched_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('learning_records', 'watch_duration',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='累计观看秒数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.add_column('subtitle_bookmarks', sa.Column('practice_count', sa.Integer(), nullable=True))
    op.add_column('video_interpretations', sa.Column('timestamp', sa.Integer(), nullable=True))
    op.alter_column('vocabularies', 'next_review_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='下次复习时间',
               existing_nullable=True)
    op.alter_column('vocabularies', 'review_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='复习次数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('vocabularies', 'last_reviewed_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='上次复习时间',
               existing_nullable=True)
    op.alter_column('vocabularies', 'ease_factor',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='SM-2易度因子',
               existing_nullable=True,
               existing_server_default=sa.text("'2.5'"))
    op.alter_column('vocabularies', 'interval_days',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='复习间隔天数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vocabularies', 'interval_days',
               existing_type=mysql.INTEGER(),
               comment='复习间隔天数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('vocabularies', 'ease_factor',
               existing_type=mysql.FLOAT(),
               comment='SM-2易度因子',
               existing_nullable=True,
               existing_server_default=sa.text("'2.5'"))
    op.alter_column('vocabularies', 'last_reviewed_at',
               existing_type=mysql.DATETIME(),
               comment='上次复习时间',
               existing_nullable=True)
    op.alter_column('vocabularies', 'review_count',
               existing_type=mysql.INTEGER(),
               comment='复习次数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('vocabularies', 'next_review_at',
               existing_type=mysql.DATETIME(),
               comment='下次复习时间',
               existing_nullable=True)
    op.drop_column('video_interpretations', 'timestamp')
    op.drop_column('subtitle_bookmarks', 'practice_count')
    op.alter_column('learning_records', 'watch_duration',
               existing_type=mysql.INTEGER(),
               comment='累计观看秒数',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_column('learning_records', 'last_watched_at')
    op.drop_column('learning_records', 'completed_at')
    # ### end Alembic commands ###
